[font]
size = 14 

[font.normal]
family = "MesloLGMDZ Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGMDZ Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGMDZ Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGMDZ Nerd Font Mono"
style = "Italic"

[window]
dimensions.columns = 100
dimensions.lines = 30
padding.x = 10
padding.y = 0

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux"]

