#!/bin/sh

if type "alacritty" &>/dev/null; then
    mkdir -p "$HOME/.config/alacritty"
    ln -sf "$PWD/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"
    ln -sf "$PWD/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
fi

