#!/bin/bash

# first time setup

# brc is short for brlntrc, my own local rc file
if [[ ! -f "$HOME/.brc" ]]; then
    touch "$HOME/.brc"
fi

if [[ ! -d "$HOME/.config" ]]; then
    mkdir -p "$HOME/.config"
fi


# setup config
ln -sf "$PWD/zshrc" "$HOME/.zshrc"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/base_bash" "$HOME/.base_bash"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/nvim" "$HOME/.config"

ln -sf "$PWD/wezterm/wezterm.lua" "$HOME/.wezterm.lua"

for i in vim alacritty; do
    cd $i && ./setup
    cd - || { echo "cd failed"; exit 1; }
done


