#!/bin/sh

EXTERNAL_ACTIVE=0

# functions to auto enable extenal display 
function ActivateExternal {
    echo "Activate External Display"
    xrandr --output eDP --off --output HDMI-A-0 --auto 
#    xrandr --output eDP --left-of HDMI-A-0 --auto 
    EXTERNAL_ACTIVE=1
}

function DeactivateExternal {
    echo "Deactivate External Display"
    xrandr --output eDP --auto --output HDMI-A-0 --off
    EXTERNAL_ACTIVE=0
}

# functions to check if external display is connected
function ExternalConnected {
    ! xrandr | grep "^HDMI-A-0" | grep disconnected
}

# functions to check if external display is active
function ExternalActive {
    [ $EXTERNAL_ACTIVE = "1" ]
}

# actual script
while true
do
    if ! ExternalActive && ExternalConnected 
    then
        ActivateExternal
    fi

    if ExternalActive && ! ExternalConnected
    then
        DeactivateExternal
    fi

    sleep 1s
done
